name: Automated Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  RELEASE_BRANCH: main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure semantic-release
        run: |
          echo "RELEASE_BRANCH value: ${RELEASE_BRANCH}"
          echo "Original config:"
          cat .github/configs/.releaserc.json
          # Try simple string replacement with sed
          sed "s/\\\${{ env.RELEASE_BRANCH }}/${RELEASE_BRANCH}/g" .github/configs/.releaserc.json > .releaserc.json
          echo "Final config after sed:"
          cat .releaserc.json

      - name: Install semantic-release dependencies
        run: |
          npm install --no-save \
            semantic-release@^24.0.0 \
            @semantic-release/github@^11.0.0 \
            @semantic-release/commit-analyzer@^13.0.0 \
            @semantic-release/release-notes-generator@^14.0.0 \
            conventional-changelog-conventionalcommits@^8.0.0

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running semantic-release..."
          echo ""

          npx semantic-release 2>&1 | tee semantic-release.log
          EXIT_CODE=$?

          echo ""
          if [ $EXIT_CODE -eq 0 ]; then
            # Check if a release was actually created
            if grep -q "There are no relevant changes, so no new version is released" semantic-release.log; then
              echo "Workflow completed successfully - No release created"
              echo "This is normal for non-releasing commits (refactor, test, build, ci, chore, style)"
            elif grep -q "Published release" semantic-release.log; then
              echo "Workflow completed successfully - Release created"
            else
              echo "Failed - Check logs above"
              exit 1
            fi
          else
            echo "Semantic-release failed with exit code $EXIT_CODE"
            echo "Failed - Check logs above"
            exit $EXIT_CODE
          fi